site_name: blog.rusiano.xyz
site_description: A personal blog
site_url: http://blog.rusiano.xyz

theme:
  name: material
  color_mode: dark
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.path
    - navigation.prune
    # - navigation.tabs.sticky

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog:
      blog_dir: .
      blog_toc: false
      archive: false

      pagination_per_page: 100

      post_readtime: false
      post_date_format: yyyy-MM-dd
      post_url_format: "{categories}/{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          short: true

      categories_name: --categories
      categories_allowed:
        - F4T
        - FUN
        - TIL
        - TIFO
        - OT

      draft_on_serve: false

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/style.css

nav:
  - blog: index.md
  - about me: about.md
  # - links: cool_links.md
  # - tags: tags.md